name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --dev
      - run: uv run ruff check .
      - run: uv run ruff format --check .

  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - run: uv sync --dev
      - run: uv run pytest -q
      - run: uv cache prune --ci

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --dev
      - run: uvx --from . docsrs-mcp --help
      - name: Test server startup
        run: |
          SERVER_PID=$(nohup uv run docsrs-mcp > server.log 2>&1 & echo $!)
          sleep 5
          curl -f http://localhost:8000/health || (cat server.log && exit 1)
          kill $SERVER_PID